### ISSUE TITLE
Delegar el Layout de App en otro componente

### ISSUE THREAD

**Issue by natoszme** [Rodrii-github/Carro-de-compras#4]
Qué nombre le ponemos?
La idea de esto es que App (proximamente Tienda o similar) tenga la menor complejidad posible (que dibuje la menor cantidad de componentes posibles)

**Comment by natoszme** [comment]
@Rodrii-github este dónde quedó resuelto?

**Comment by Rodrii-github** [comment]
No deje app solo con shop, no era eso?? Te acorda que estaba toda la logica
ahi y lo pase a cada componente o no era eso?
