### ISSUE TITLE
Mostrar subtotales y totales en el detalle del carro

### ISSUE THREAD

**Issue by natoszme** [Rodrii-github/Carro-de-compras#9]
Para ver
- cuánto estoy pagando por tipo de producto
- cuánto voy en total

**Comment by natoszme** [comment]
Faltaría mostrar el subtotal de cada item (`precio * cantidad`).
En el total, también falta multiplicar por la cantidad de cada item

**Comment by Rodrii-github** [comment]
Ahh okey solo le hice el precio total, corrijo eso
